apiVersion: apps/v1
kind: Deployment
metadata:
        name: depl-http-2
        labels:
                app: http2
spec:
        replicas: 2
        selector:
                matchLabels:
                        app: http2
        template:
                metadata:
                        labels:
                                app: http2
                spec:
                        containers:
                                - name: http
                                  image: jhjhjh/myubuntu_depl_2:0.4
                                  imagePullPolicy: Always
                                  ports:
                                        - containerPort: 8099

