apiVersion: apps/v1
kind: Deployment
metadata:
        name: depl-http-1
        labels:
                app: http1
spec:
        replicas: 2
        selector:
                matchLabels:
                        app: http1
        template:
                metadata:
                        labels:
                                app: http1
                spec:
                        containers:
                                - name: http
                                  image: jhjhjh/myubuntu:0.3
                                  imagePullPolicy: Always
                                  ports:
                                        - containerPort: 8099

