apiVersion: v1
kind: Service
metadata:
  name: http2
  labels:
    app: http2
spec:
  type: NodePort
  selector:
    app: http2
  ports:
    - name: http
      protocol: TCP
      port: 8099
      targetPort: 8099
      nodePort: 30001
