apiVersion: v1
kind: Service
metadata:
  name: http1
  labels:
    app: http1
spec:
  type: NodePort
  selector:
    app: http1
  ports:
    - name: http
      protocol: TCP
      port: 8099
      targetPort: 8099
      nodePort: 30000
